name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latexmk and xelatex
      run: sudo apt install -y latexmk texlive-xetex
    - name: Extract fonts
      run:
        cd "Project report"
        unzip fonts.zip
    - name: Build with latexmk
      run: |
        cd "Project report"
        latexmk
    - name: Build with xelatex and bibtex
      run: |
        cd "Project report"
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
        bibtex full-report
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
    - uses: actions/upload-artifact@v2
      with:
        name: project-report.pdf
        path: "Project report/build/full-report.pdf"
  build-coop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latexmk and xelatex
      run: sudo apt install -y latexmk texlive-xetex
    - name: Extract fonts
      run:
        cd "Project report"
        unzip fonts.zip
    - name: Build with latexmk
      run: |
        cd "COOP report"
        latexmk
    - name: Build with xelatex and bibtex
      run: |
        cd "COOP report"
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
        bibtex full-report
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
        xelatex -synctex=1 -interaction=nonstopmode full-report.tex
    - uses: actions/upload-artifact@v2
      with:
        name: project-report.pdf
        path: "COOP report/build/full-report.pdf"
